default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: photos_development
test:
  <<: *default
  database: photos_test
production:
  <<: *default
  database: photos_production
  username: photos
  password: <%= ENV['PHOTOS_DATABASE_PASSWORD'] %>
